# Generated by Django 4.2.1 on 2023-05-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bot',
            table='myapp_bot',
        ),
    ]
